chore: add-lint-to-pipeline
snyk/code-client pull request #135
Opened 2022-03-20 08:50 UTC by shirlupo

- [ ] Ready for review
- [ ] Linked to Jira ticket

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### Screenshots

#### Additional questions

2022-03-21 09:00 UTC, pkey requested changes

2022-03-21 09:00 UTC, pkey commented on package.json
> +    "lint": "npx eslint 'src/**/*.ts'",
[suggestion] I suggest adding `tsc --noEmit` to the lint step as well. Not sure if `eslint` actually covers compilation part.

2022-03-27 10:01 UTC, shirlupo commented on .circleci/config.yml
> +            - test
@pkey  fixed :) tnx for the feedback

2022-03-28 07:26 UTC, metju90 approved these changes

2022-03-28 08:05 UTC, pkey approved these changes

2022-03-28 08:06 UTC, merged

2022-03-29 10:41 UTC, snyksec commented
:tada: This PR is included in version 4.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@snyk/code-client/v/4.9.0)
- [GitHub release](https://github.com/snyk/code-client/releases/tag/v4.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: